export const XP_VALUES = {
  REPORT_CREATED: 5,
  REPORT_APPROVED: 25,
  VERIFICATION_COMPLETED: 20,
  HIGH_CONFIDENCE_BONUS: 10,
  AREA_BONUS: 15,
  DAILY_LOGIN: 2,
  MILESTONE_10_RESOLVED: 50,
  FAKE_REPORT: -20,
  FAKE_VERIFICATION: -15,
} as const;
